### ISSUE TITLE
Demon turn counter not shown if above 1000

### ISSUE THREAD

**Issue by emilhem** [subchannel13/EnchantedFortress#10]
I'm using LineageOS (basically Android) 7.1.2 on a One Plus X (onyx) and when the demon counter is above 1000 it doesn't display the number of turns. This was confusing for me since I thought that I would win if I selected that option.

**Comment by subchannel13** [comment]
Oh, built it yourself :)? Can you provide screenshot of the problem?

**Comment by mueller-ma** [comment]
Can confirm population not going over 100000.
Lineageos on oneplusx. Android 7.1.2

**Comment by subchannel13** [comment]
@mueller-ma That's by design, population and walls are limited to 100000. What emilhem describes doesn't relate to that limit.

**Comment by subchannel13** [comment]
Is this still happening? I have neither a device or OS as issue reporter and on my devices the issue doesn't happen. Can screenshot be provided?

**Comment by subchannel13** [comment]
Closing, unfortunately. I cannot reproduce and submitter is not responding to requests for more information.
