### ISSUE TITLE
(A sort of) Feature Request: Debug logging

### ISSUE THREAD

**Issue by sm4rk0** [subchannel13/EnchantedFortress#11]
Optional "enable logging" setting (or always log, if no setting) and possibility to send the log file attached in an email to the author would be useful. It would contain the game state in each step so any particular situation could be reproduced. While this is more useful to the developer(s) than the average user, all of us would benefit from it as bugs would be easier to catch and solve.

**Comment by subchannel13** [comment]
It was planned I might add it in next v1.2 version. I thought about using standard Android logs which can be observed and collected with aLogcat app.

**Comment by subchannel13** [comment]
Included in v1.9
