### ISSUE TITLE
Incorrect usage of LGPL license

### ISSUE THREAD

**Issue by emilhem** [subchannel13/EnchantedFortress#12]
First a question, are you sure that you want to use LGPL? Why not GPL? LGPL allows commercial use for others. You can still use the code for commercial purposes yourself with the regular GPL license.

The issue with your current license setup with LGPL is that the GPL part is missing. You only have the LGPL part which isn't complete without the GPL license to accompany it. Read more about how to use the license here: https://www.gnu.org/licenses/gpl-howto.html

**Comment by subchannel13** [comment]
You are right, will correct in next version.

**Comment by subchannel13** [comment]
Corrected in v1.2
