### ISSUE TITLE
FR: Round and Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [subchannel13/EnchantedFortress#19]

**Comment by subchannel13** [comment]
Square icon needs face lift too, will make round one too.

**Comment by mueller-ma** [comment]
Oreo introduced adaptive icons.

**Comment by subchannel13** [comment]
LoL, look at https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html! Last two images are real perversion :). Wish they spend as much effort on under the hood stuff as they do on non-backward compatible face lift. Although the feature looks cool and saves me from making an icon twice, I'm not going to use it until they make it backwards compatible with older versions.

**Comment by mueller-ma** [comment]
>  I'm not going to use it until they make it backwards compatible with older versions.

That wont happen. But in 2-3 years many most people will use Oreo

**Comment by subchannel13** [comment]
Quite likely :). In the mean time Andriod Dashboard (https://developer.android.com/about/dashboards/index.html) suggests supporting at least Lollipop but I should include Kitkat and Jelly Bean if I can. If only they chose different XML tag for adaptive icon then one used for old square icon then there wouldn't be any problem.

**Comment by mueller-ma** [comment]
Kitkat was released 2013 and still has 16%. Yeah Android Updates ;)

**Comment by mueller-ma** [comment]
> Next you must create alternative drawable resources in your app for use with Android 8.0 (API level 26) in res/mipmap-anydpi/ic_launcher.xml

Sounds to me that you can have the old icons as png and the new ones as xml.

**Comment by subchannel13** [comment]
I'll have to read more about it. I glanced somewhere that fallback should be done a certain way which was not supported in lower versions. Probably more wisdom surfaced in the mean time (since that article was written).

**Comment by mueller-ma** [comment]
Any updates to the adaptive icon?

**Comment by subchannel13** [comment]
Hi @mueller-ma! No, not much activity on this project recently, real life got more demanding than usual.

**Comment by subchannel13** [comment]
@mueller-ma I've added adaptive icon to dev branch.

**Comment by mueller-ma** [comment]
@subchannel13 Thanks! I'm not yet on android 8, but I can test it as soon as I get the update.
