### ISSUE TITLE
FR dark theme

### ISSUE THREAD

**Issue by mueller-ma** [subchannel13/EnchantedFortress#23]

**Comment by subchannel13** [comment]
Finally got around to tackle this. It turns out it's very easy to make switch between day and night mode when the system does. @mueller-ma is that enough or do you expect in-app settings for switching between modes?

**Comment by mueller-ma** [comment]
A setting would be appreciated. The following link helped me in the past to implement this: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app
