### ISSUE TITLE
Hall of fame mixes together victoties and defeats.

### ISSUE THREAD

**Issue by vi** [subchannel13/EnchantedFortress#33]
It should have a third column: game result. Sorting order should be ascending number of moves for victories, then descending number of moves for defeats. Difficulties should have separate tables.

Current hall of fame is useless and may be cleared upon update (unless the game outcome is actually stored invisibly inside).

**Comment by subchannel13** [comment]
Argh, how??? Will check what's a deal with victory/defeat check at the first glance looks OK with small probability of hitting decimal [0, 1] population.

**Comment by mueller-ma** [comment]
You could somehow calculate a score than multiply it with e.g 0.5 for easy and 1.5 for hard. This way you dont really need seperate tables for the difficulties.

**Comment by vi** [comment]
Currently the table looks like:

```
Turns | Difficulty
21 | Hard
23 | Hard
48 | Hard
64 | Hard
79 | Hard
54 | Normal
```

Only two of them (or even one?) are victories? And it's definitely not the "first place" "21 turns".

It should be like this:

```
Turns | Difficulty | Outcome
64 | Hard | Victory
79 | Hard | Victory
48 | Hard | Defeat
54 | Normal | Defeat
23 | Hard | Defeat
21 | Hard | Defeat
```

I.e. the outcome is visible and the shorter victorious game is the better, the longer unsuccessful game is the better.

**Comment by subchannel13** [comment]
I run the code through debugger, when player losses his population will routinely be in [0, 1> range. I'll fix victory condition check and try to lose sometimes :D.

@mueller-ma I'd still like to have multiple difficulty levels present, Minesweeper style :). I don't have an idea of good scoring system and I can remove difficulty column by making it table header, one table for each level. I would have done it in previous version if I wasn't so rusty with custom "adapters".

@vi I find it wrong to put defeats in hall of fame, what is famous about them, but if you like it I can turn the bug into a feature :).

**Comment by vi** [comment]
Also the hall seems to be short-ish: only 5 entries? Should be at least 10-20.

Also in addition to the list of best games there can be other statistical data: {maximum,median,minimum,average} {number of moves,walls,population,researsh level} at time of {the win,the lose}.
