### ISSUE TITLE
FR: showing victims in red.

### ISSUE THREAD

**Issue by vi** [subchannel13/EnchantedFortress#34]
Messages about attacks may be styled depending on desirability of progressing.

**Comment by subchannel13** [comment]
The way how messages are displayed is changed 1.10 dev version. I'll make it a bit more prominent when a battle happens but basically it's done in a dev branch.

**Comment by subchannel13** [comment]
1.10 was delivered a while ago, forgot to close the issue. If you want further changes to this feel free to reopen the issue,
