### ISSUE TITLE
Victory or defeat screen should also show turn counter.

### ISSUE THREAD

**Issue by vi** [subchannel13/EnchantedFortress#39]

**Comment by vi** [comment]
Also when mashing the "Finish move" button, one should not skip the screen and go back to menu without even knowing if it was a victory or defeat.

Either the "back to main menu" button should appear in some other place (not where "Finish the move" button resides) or the main menu should show the last game result like "win in 90 moves".

**Comment by subchannel13** [comment]
Added both. When game ends, one way or another, population distribution controls are removed and as consequence "Finish move" button jumps up.

**Comment by vi** [comment]
> population distribution controls are removed

But not the counters themselves?

**Comment by subchannel13** [comment]
@vi Turn number, population and wall count stay on screen.
