### ISSUE TITLE
Sluggish application quit by back button

### ISSUE THREAD

**Issue by vi** [subchannel13/EnchantedFortress#4]
It requires multiple presses of the back button in main menu to quit application after finishing the game. Buttons get increasingly darker as I keep on pressing the back button. The more games I played, the more presses of the back button it requires to quit.

**Comment by subchannel13** [comment]
Managed to reproduce it, probably incorrect fragment handling logic.

**Comment by subchannel13** [comment]
Fixed in v1.1.
