### ISSUE TITLE
FR: Include metadata for fdroid

### ISSUE THREAD

**Issue by mueller-ma** [subchannel13/EnchantedFortress#43]
When providing metadata via a fastlane directory, fdroid automaticly shows them in the store. You dont need to install fastlane, just create the folder

Example: https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US
Info: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

**Comment by subchannel13** [comment]
Will check it out. I couldn't find if F-Droid has any additional "store front" data like screenshot, news and change log. Their documentation is scattered and focused more on how to host the service rather then how to use it.

**Comment by mueller-ma** [comment]
You could copy the folder from gadgetbridge and replace everything in it. It seems to be complete.

**Comment by subchannel13** [comment]
> 
> 
> Documentation is here: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

Yes, yes, I know :). I'm pondering idea for making a script to convert changelog.md to fastlane to reduce duplication. I'll put one day aside to tackle this. But in any case this FR is planned for current version.

**Comment by mueller-ma** [comment]
For https://github.com/openhab/openhab-android I wrote a simple script that is executed by travis after tagging a release (https://github.com/openhab/openhab-android/blob/master/travis/uploads.sh#L22). It's downloading the changelog from the github release, puts it into the fastlane files, commits, pushes and tags a new release (`<version>-fdroid`). F-Droid only pics up `*-fdroid` tags for openHAB android.

**Comment by subchannel13** [comment]
Hi all, long time no see! :)

I've pushed this (fastlane style changelogs) to dev branch. Is there a way to verify before release if it is done correctly?

**Comment by mueller-ma** [comment]
I'm not aware of a way to check this. I've seen that you didn't push screenshots and descriptions to the metadata. Is this intended?

**Comment by subchannel13** [comment]
That will come later this week. Then I'll hope it's set up well. Shame F-Droid can't work with normal changelogs like one described here: https://keepachangelog.com/en/1.0.0/

**Comment by subchannel13** [comment]
I've added descriptions and screenshots, took me a while to finish something in other hobby project before I got back to this one. @mueller-ma what is featureGraphic image for?

**Comment by mueller-ma** [comment]
It's the image at the top of the F-Droid entry. You can look at https://support.google.com/googleplay/android-developer/answer/1078870 for the required size.
