### ISSUE TITLE
Feature request: turn counter + minimum winning

### ISSUE THREAD

**Issue by vi** [subchannel13/EnchantedFortress#5]
The game should display turn counter. It should also remember the minimal number of turns the game was won in so far.

**Comment by subchannel13** [comment]
Game already tracks turn count but for some reason I didn't put it on UI. Will do it in v1.1 but I'm not sure for the other part. I'd rather have it on some sort of "high scores" screen then as a single number randomly listed somewhere. That feature will wait a bit.

**Comment by subchannel13** [comment]
Second part, hall of fame is finally introduced in v1.7.
