### ISSUE TITLE
Enchanted fortress app crashes when I click on any option in landscape mode.

### ISSUE THREAD

**Issue by pzdawood** [subchannel13/EnchantedFortress#50]
### Actual behaviour
When I open the enchanted fortress app in portable mode and  rotate my phone in landscape mode. After that I click on any option app suddenly crashes.
### How to reproduce
* Download the enchanted fortress app from F-driod.
* Install this app.
* Open the enchanted fortress app in Portable mode.
* Rotate your phone in landscape mode.
* Click on any option app suddenly crashes.
* Browser: enchanted fortress.
* Version: 1.9
* Operating system: 7.1.2
### Recording of the bug
https://youtu.be/ngXI2-rKCIA

**Comment by subchannel13** [comment]
Hi!

Video got blocked by Youtube for breaking terms of service. What is portable mode? I can't find any documentation on it and Google thinking I mean something else with a word "portable" (like portable device or portable PC application) doesn't help either. I found some forum reference to an issue with native code execution but this app doesn't do any of that explicitly. Also I can't reproduce it by normally running it on my device.

Can you get Logcat logs for hr.kravarscan.enchantedfortress?

BR,
Ivan

**Comment by mueller-ma** [comment]
He means "Portrait mode". I can reproduce this crash with the same Android version.

**Comment by subchannel13** [comment]
Ok, got it reproduced.

**Comment by pzdawood** [comment]
Can I put gif in place of video

**Comment by subchannel13** [comment]
@pzdawood no need, got it reproduced. After updating app from F-Droid for some reason it started to happen with both my local and F-Driod build while local build worked fine before. Will check logs on my end.

**Comment by subchannel13** [comment]
Found the cause and pushed a fix. Will close the issue when v1.10 becomes available at F-Droid.
