### ISSUE TITLE
Graphics!

### ISSUE THREAD

**Issue by eyalroz** [subchannel13/EnchantedFortress#55]
This game really needs some graphics. Even if it's just a few static photos for certain events; or icons for the research menu entries, and the kinds of workers; or visual percentage-bars for the allocation of townspeople to different roles.

**Comment by subchannel13** [comment]
I know but my drawing skills are pretty bad. If I get some time try to make something out.

**Comment by eyalroz** [comment]
I think there are websites where you can solicit people to volunteer to help with graphics for FOSS projects. If nowhere else - you could try on the www.wesnoth.org forums, they have contacts with a bunch of people who contribute graphics to that one. (You do know Wesnoth I assume?)

**Comment by subchannel13** [comment]
Yes, I've played it. Neat graphics, ok gameplay (not that big fan of 60% accuracy being "high markmanship" but I'm sucker for units leveling up), UI not that great on a phone but would play it one day to see the story.

I guess I should actively seek help where I lack skill. There are few contributors who help with german and french translation and one of them mentioned a site where people help with localization. Wouldn't be surprised if the same exists for graphics. But I lack time to manage it, you can see that from recent commit frequency. Expanding family, real life obligations, big passion project (4X game), "for reals" project (also 4X game) and full time job fill my day.

**Comment by eyalroz** [comment]
So... did you add some graphics eventually?

**Comment by subchannel13** [comment]
No. I don't have neither ability to either do it on my own nor time and will to seek out help, at least in the near term future. I may make an icon or two now and then but this issue is too broad to ever satisfy and that's one reason to close it.
