### ISSUE TITLE
Feature request: difficulty levels.

### ISSUE THREAD

**Issue by vi** [subchannel13/EnchantedFortress#6]
After completing it a couple of times, it got rather trivial.

Maybe there should be more difficult modes?

Ideally there should be two axes: hardness (speed of demon reproduction, agressiveness of their attacks, initial delay before first demon attack) and trickiness (number of professions and kinds of demons).

**Comment by subchannel13** [comment]
Good idea, I'll consider it for future update.

**Comment by subchannel13** [comment]
Added in v1.3, at least hardness part. Trickiness would require some new game mechanics.
